plugins {
	id "base"
	id "org.jetbrains.kotlin.jvm" apply false // https://youtrack.jetbrains.com/issue/KT-30276
}

description = "Spring Boot Build"

defaultTasks 'build'

allprojects {
	group = "org.springframework.boot"
}

subprojects {
	apply plugin: "org.springframework.boot.conventions"

	repositories {
		mavenLocal()
		mavenCentral()
		spring.mavenRepositories()
	}

	configurations.all {
		resolutionStrategy.cacheChangingModulesFor 0, "minutes"
	}
}

tasks.withType(JavaCompile) {
	options.encoding = 'UTF-8'
}

// 直接排除不需要构建的模块
def excludedProjects = [':spring-boot-docs', ':spring-boot-system-tests', ':spring-boot-tests']
gradle.projectsLoaded {
	subprojects.findAll { excludedProjects.forEach {excludedProject->it.name.contains(excludedProject)} }.each {
		it.tasks.all { task ->
			task.enabled = false // 禁用该项目的所有任务
		}
	}
}